import type { DevotionGuide, Prayer } from "./prayers";

/** A supplementary treasury of historic Catholic prayers. */
export const treasuryPrayers: Prayer[] = [
  {
    slug: "nicene-creed",
    title: "Nicene Creed",
    category: "Essential",
    form: "Creed",
    latinTitle: "Symbolum Nicaenum",
    keywords: ["creed", "profession of faith", "trinity", "incarnation"],
    summary: "Profess the faith of the Church in the Holy Trinity and the saving work of Christ.",
    whenToPray: "On Sundays, solemnities, and whenever renewing the faith",
    source: "Niceno-Constantinopolitan Creed; historic public-domain English form",
    text: [
      "I believe in one God, the Father almighty, Maker of heaven and earth, and of all things visible and invisible.",
      "And in one Lord Jesus Christ, the only-begotten Son of God, born of the Father before all ages; God of God, Light of Light, true God of true God; begotten, not made; consubstantial with the Father; by whom all things were made.",
      "Who for us men and for our salvation came down from heaven; and was incarnate by the Holy Ghost of the Virgin Mary, and was made man. He was crucified also for us, suffered under Pontius Pilate, and was buried. And the third day He rose again according to the Scriptures. And He ascended into heaven, and sitteth at the right hand of the Father. And He shall come again with glory to judge the living and the dead; of whose kingdom there shall be no end.",
      "And I believe in the Holy Ghost, the Lord and Giver of life, who proceedeth from the Father and the Son; who together with the Father and the Son is adored and glorified; who spoke by the prophets.",
      "And one holy, Catholic, and Apostolic Church. I confess one Baptism for the remission of sins. And I look for the resurrection of the dead, and the life of the world to come. Amen.",
    ],
  },
  {
    slug: "act-of-adoration",
    title: "Act of Adoration",
    category: "Essential",
    form: "Prayer",
    latinTitle: "Actus Adorationis",
    keywords: ["adoration", "praise", "worship", "majesty"],
    summary: "Adore God as Creator, sovereign Lord, and final end.",
    whenToPray: "At the beginning of prayer or before the Blessed Sacrament",
    source: "Traditional Catholic act; public-domain English form",
    text: [
      "O my God, I adore Thee, and I acknowledge Thee to be my Creator, my sovereign Lord, and my last end. I bow down before Thy infinite majesty, and I offer Thee the homage of my whole being. Thou alone art worthy of all honor, glory, and love, now and for ever. Amen.",
    ],
  },
  {
    slug: "act-of-thanksgiving",
    title: "Act of Thanksgiving",
    category: "Essential",
    form: "Prayer",
    latinTitle: "Actus Gratiarum Actionis",
    keywords: ["thanksgiving", "gratitude", "benefits", "providence"],
    summary: "Thank God for creation, redemption, and every gift of grace.",
    whenToPray: "After prayer, after receiving a grace, or at the close of day",
    source: "Traditional Catholic act; public-domain English form",
    text: [
      "O my God, I thank Thee with my whole heart for all the benefits which Thou hast bestowed upon me: for creating and preserving me, for redeeming me by the Precious Blood of Thy Son, for calling me to the true faith, and for all the graces Thou hast given me, known and unknown.",
      "May all that I am and all that I possess praise Thee. Grant that I may use Thy gifts faithfully and at last give Thee thanks with the saints in heaven for ever. Amen.",
    ],
  },
  {
    slug: "act-of-reparation",
    title: "Act of Reparation",
    category: "Essential",
    form: "Prayer",
    latinTitle: "Actus Reparationis",
    keywords: ["reparation", "atonement", "sin", "sacred heart"],
    summary: "Offer love and sorrow to Christ in reparation for sin and neglect.",
    whenToPray: "On Fridays, during adoration, or after recognizing sin",
    source: "Traditional Catholic act; public-domain English form",
    text: [
      "O most loving Jesus, I offer Thee the love of my poor heart in reparation for every offense committed against Thee. I grieve for the coldness, ingratitude, and sin by which Thy love is wounded.",
      "Unite my prayer, work, joy, and suffering to Thy perfect offering upon the Cross. Receive them for the honor of Thy Father, the conversion of sinners, and the salvation of souls. Amen.",
    ],
  },
  {
    slug: "magnificat",
    title: "Canticle of the Blessed Virgin Mary",
    category: "Daily rhythm",
    form: "Canticle",
    latinTitle: "Magnificat",
    keywords: ["mary", "evening", "vespers", "canticle", "gratitude"],
    summary: "Magnify the Lord with Mary for His mercy and mighty deeds.",
    whenToPray: "In the evening, especially at Evening Prayer",
    source: "Luke 1:46-55; Douay-Rheims public-domain English",
    text: [
      "My soul doth magnify the Lord. And my spirit hath rejoiced in God my Saviour.",
      "Because He hath regarded the humility of His handmaid; for behold from henceforth all generations shall call me blessed. Because He that is mighty hath done great things to me; and holy is His name.",
      "And His mercy is from generation unto generations, to them that fear Him. He hath showed might in His arm: He hath scattered the proud in the conceit of their heart.",
      "He hath put down the mighty from their seat, and hath exalted the humble. He hath filled the hungry with good things; and the rich He hath sent empty away.",
      "He hath received Israel His servant, being mindful of His mercy: as He spoke to our fathers, to Abraham and to his seed for ever.",
      "Glory be to the Father, and to the Son, and to the Holy Ghost; as it was in the beginning, is now, and ever shall be, world without end. Amen.",
    ],
  },
  {
    slug: "benedictus",
    title: "Canticle of Zachary",
    category: "Daily rhythm",
    form: "Canticle",
    latinTitle: "Benedictus Dominus Deus Israel",
    keywords: ["zachary", "zechariah", "morning", "lauds", "canticle"],
    summary: "Bless God for visiting His people and raising up salvation in Christ.",
    whenToPray: "In the morning, especially at Morning Prayer",
    source: "Luke 1:68-79; Douay-Rheims public-domain English",
    text: [
      "Blessed be the Lord God of Israel; because He hath visited and wrought the redemption of His people. And hath raised up a horn of salvation to us, in the house of David His servant.",
      "As He spoke by the mouth of His holy prophets, who are from the beginning: salvation from our enemies, and from the hand of all that hate us; to perform mercy to our fathers, and to remember His holy testament.",
      "The oath which He swore to Abraham our father, that He would grant to us, that being delivered from the hand of our enemies, we may serve Him without fear, in holiness and justice before Him, all our days.",
      "And thou, child, shalt be called the prophet of the Highest: for thou shalt go before the face of the Lord to prepare His ways; to give knowledge of salvation to His people, unto the remission of their sins.",
      "Through the bowels of the mercy of our God, in which the Orient from on high hath visited us: to enlighten them that sit in darkness and in the shadow of death; to direct our feet into the way of peace.",
      "Glory be to the Father, and to the Son, and to the Holy Ghost; as it was in the beginning, is now, and ever shall be, world without end. Amen.",
    ],
  },
  {
    slug: "te-deum",
    title: "Te Deum",
    category: "Daily rhythm",
    form: "Hymn",
    latinTitle: "Te Deum Laudamus",
    keywords: ["thanksgiving", "praise", "church", "canticle", "solemn"],
    summary: "Join heaven and earth in the Church's ancient hymn of praise and thanksgiving.",
    whenToPray: "On feasts, anniversaries, and occasions of solemn thanksgiving",
    source: "Ancient Latin hymn; historic public-domain English form",
    text: [
      "We praise Thee, O God; we acknowledge Thee to be the Lord. All the earth doth worship Thee, the Father everlasting.",
      "To Thee all Angels cry aloud; the heavens and all the powers therein. To Thee Cherubim and Seraphim continually do cry: Holy, Holy, Holy, Lord God of Sabaoth. Heaven and earth are full of the majesty of Thy glory.",
      "The glorious choir of the Apostles praise Thee. The admirable company of the Prophets praise Thee. The white-robed army of Martyrs praise Thee. The holy Church throughout all the world doth acknowledge Thee: the Father of infinite majesty; Thy adorable, true, and only Son; also the Holy Ghost, the Comforter.",
      "Thou art the King of glory, O Christ. Thou art the everlasting Son of the Father. When Thou tookest upon Thee to deliver man, Thou didst not abhor the Virgin's womb. When Thou hadst overcome the sharpness of death, Thou didst open the kingdom of heaven to all believers.",
      "Thou sittest at the right hand of God, in the glory of the Father. We believe that Thou shalt come to be our Judge. We therefore pray Thee, help Thy servants, whom Thou hast redeemed with Thy Precious Blood. Make them to be numbered with Thy saints in glory everlasting.",
      "O Lord, save Thy people, and bless Thine inheritance. Govern them and lift them up for ever. Day by day we bless Thee; and we praise Thy name for ever, yea, for ever and ever.",
      "Vouchsafe, O Lord, this day to keep us without sin. Have mercy upon us, O Lord, have mercy upon us. Let Thy mercy, O Lord, be upon us, as we have hoped in Thee. O Lord, in Thee have I hoped; let me never be confounded.",
    ],
  },
  {
    slug: "traditional-evening-prayer",
    title: "Traditional Evening Prayer",
    category: "Daily rhythm",
    form: "Prayer",
    keywords: ["evening", "night", "thanksgiving", "examen", "rest"],
    summary: "Close the day with adoration, thanksgiving, sorrow, and trust.",
    whenToPray: "At the close of the day",
    source: "Traditional Catholic evening prayer; public-domain English form",
    text: [
      "O my God, I adore Thee, and I love Thee with my whole heart. I thank Thee for having created me, made me a Christian, and preserved me this day.",
      "Pardon the evil I have done, and if I have done any good, accept it. Take care of me while I sleep, and deliver me from all danger. May Thy grace be always with me and with all whom I love. Amen.",
    ],
  },
  {
    slug: "visit-this-house",
    title: "Prayer Before Sleep",
    category: "Daily rhythm",
    form: "Prayer",
    latinTitle: "Visita, Quaesumus, Domine",
    keywords: ["sleep", "night", "house", "angels", "protection"],
    summary: "Ask the Lord and His angels to guard the household through the night.",
    whenToPray: "Immediately before sleep",
    source: "Traditional Roman night prayer; public-domain English form",
    text: [
      "Visit, we beseech Thee, O Lord, this dwelling, and drive far from it all snares of the enemy. Let Thy holy Angels dwell herein to preserve us in peace; and let Thy blessing be always upon us. Through Christ our Lord. Amen.",
    ],
  },
  {
    slug: "prayer-to-the-holy-trinity",
    title: "Prayer to the Most Holy Trinity",
    category: "Christ & Trinity",
    form: "Prayer",
    latinTitle: "Oratio ad Sanctissimam Trinitatem",
    keywords: ["trinity", "father", "son", "holy ghost", "adoration"],
    summary: "Adore the one God in three divine Persons and surrender the whole self to Him.",
    whenToPray: "On Sundays, Trinity Sunday, or in quiet adoration",
    source: "Traditional Catholic prayer; public-domain English form",
    text: [
      "O most Holy Trinity, Father, Son, and Holy Ghost, one God in three Persons, I adore Thee profoundly. I offer Thee my body and soul, my thoughts, words, and deeds, and all that I am and have.",
      "Keep me in Thy grace, preserve me from sin, and grant that every breath of my life may praise Thy unity in Trinity and Thy Trinity in unity. Amen.",
    ],
  },
  {
    slug: "prayer-before-a-crucifix",
    title: "Prayer Before a Crucifix",
    category: "Christ & Trinity",
    form: "Prayer",
    latinTitle: "En Ego, O Bone et Dulcissime Iesu",
    keywords: ["crucifix", "passion", "five wounds", "contrition", "faith hope charity"],
    summary: "Contemplate the wounds of Christ and ask for faith, hope, charity, and true contrition.",
    whenToPray: "Before a crucifix, especially on Fridays or during Lent",
    source: "Traditional prayer before a crucifix; public-domain English form",
    text: [
      "Behold, O kind and most sweet Jesus, I cast myself upon my knees in Thy sight, and with the most fervent desire of my soul I pray and beseech Thee that Thou wouldst impress upon my heart lively sentiments of faith, hope, and charity, true repentance for my sins, and a firm purpose of amendment.",
      "While with deep affection and grief of soul I ponder within myself and mentally contemplate Thy five most precious wounds, having before mine eyes that which David the prophet spoke concerning Thee: They have pierced My hands and My feet; they have numbered all My bones. Amen.",
    ],
  },
  {
    slug: "veni-creator-spiritus",
    title: "Come, Creator Spirit",
    category: "Holy Spirit",
    form: "Hymn",
    latinTitle: "Veni Creator Spiritus",
    keywords: ["holy ghost", "holy spirit", "hymn", "pentecost", "seven gifts"],
    summary: "Invoke the Creator Spirit for light, strength, peace, and the knowledge of God.",
    whenToPray: "At Pentecost, before important work, or when seeking the Spirit's guidance",
    source: "Ancient Latin hymn; traditional public-domain English verse",
    text: [
      "Come, Holy Ghost, Creator blest, and in our souls take up Thy rest; come with Thy grace and heavenly aid to fill the hearts which Thou hast made.",
      "O Comforter, to Thee we cry, O heavenly Gift of God Most High, O Fount of life and Fire of love, and sweet Anointing from above.",
      "Thou in Thy sevenfold gifts art known; Thou, finger of God's hand, we own; Thou, promise of the Father, Thou who dost the tongue with power imbue.",
      "Kindle our senses from above, and make our hearts overflow with love; with patience firm and virtue high the weakness of our flesh supply.",
      "Far from us drive the foe we dread, and grant us Thy true peace instead; so shall we not, with Thee for guide, turn from the path of life aside.",
      "Oh, may Thy grace on us bestow the Father and the Son to know, and Thee, through endless times confessed, of both the eternal Spirit blest.",
      "All glory while the ages run be to the Father and the Son, who rose from death; the same to Thee, O Holy Ghost, eternally. Amen.",
    ],
  },
  {
    slug: "veni-sancte-spiritus",
    title: "Come, Holy Spirit",
    category: "Holy Spirit",
    form: "Hymn",
    latinTitle: "Veni Sancte Spiritus",
    keywords: ["holy ghost", "holy spirit", "sequence", "pentecost", "consoler"],
    summary: "Welcome the Holy Spirit as Light, Consoler, Healer, and Giver of gifts.",
    whenToPray: "At Pentecost or whenever asking for renewal and consolation",
    source: "Medieval Pentecost sequence; traditional public-domain English verse",
    text: [
      "Come, Holy Spirit, come! And from Thy celestial home shed a ray of light divine. Come, Father of the poor! Come, source of all our store! Come, within our bosoms shine.",
      "Thou, of comforters the best; Thou, the soul's most welcome Guest; sweet refreshment here below. In our labor, rest most sweet; grateful coolness in the heat; solace in the midst of woe.",
      "O most blessed Light divine, shine within these hearts of Thine, and our inmost being fill. Where Thou art not, man hath naught, nothing good in deed or thought, nothing free from taint of ill.",
      "Heal our wounds, our strength renew; on our dryness pour Thy dew; wash the stains of guilt away. Bend the stubborn heart and will; melt the frozen, warm the chill; guide the steps that go astray.",
      "On the faithful, who adore and confess Thee evermore, in Thy sevenfold gift descend. Give them virtue's sure reward; give them Thy salvation, Lord; give them joys that never end. Amen. Alleluia.",
    ],
  },
  {
    slug: "prayer-for-the-seven-gifts",
    title: "Prayer for the Seven Gifts of the Holy Ghost",
    category: "Holy Spirit",
    form: "Prayer",
    latinTitle: "Oratio pro Septem Donis Spiritus Sancti",
    keywords: ["seven gifts", "wisdom", "understanding", "counsel", "fortitude", "knowledge", "piety", "fear of the lord"],
    summary: "Ask the Holy Ghost to perfect the soul through His seven gifts.",
    whenToPray: "Before Confirmation, during a Pentecost novena, or in discernment",
    source: "Traditional Catholic prayer; public-domain English form",
    text: [
      "Come, Holy Ghost, Spirit of wisdom, and teach me to value rightly the things of heaven. Come, Spirit of understanding, and enlighten my mind with the light of divine truth.",
      "Come, Spirit of counsel, and guide me in the way of salvation. Come, Spirit of fortitude, and give me courage to overcome every obstacle to holiness.",
      "Come, Spirit of knowledge, and teach me to use created things for the glory of God. Come, Spirit of piety, and make my service of God loving and filial.",
      "Come, Spirit of holy fear, and keep me in reverent awe of offending God. Adorn me with Thy gifts, bring forth in me Thy fruits, and make me a faithful temple of Thy presence. Amen.",
    ],
  },
  {
    slug: "prayer-before-mass",
    title: "Prayer Before Mass",
    category: "Eucharistic",
    form: "Prayer",
    latinTitle: "Omnipotens Sempiterne Deus",
    keywords: ["mass", "communion", "preparation", "saint thomas aquinas", "eucharist"],
    summary: "Approach the Eucharistic mystery with humility, faith, purity, and desire.",
    whenToPray: "Before assisting at Mass or receiving Holy Communion",
    source: "Traditional prayer of Saint Thomas Aquinas before Mass; public-domain English form",
    text: [
      "Almighty and everlasting God, behold, I approach the Sacrament of Thine only-begotten Son, our Lord Jesus Christ. I approach as one sick to the Physician of life; as one unclean to the Fountain of mercy; as one blind to the Light of eternal brightness; as one poor and needy to the Lord of heaven and earth.",
      "Therefore I implore the abundance of Thy measureless bounty, that Thou wouldst vouchsafe to heal my infirmity, wash my uncleanness, enlighten my blindness, enrich my poverty, and clothe my nakedness; that I may receive the Bread of Angels, the King of kings and Lord of lords, with such reverence and humility, with such contrition and devotion, with such purity and faith, and with such purpose and intention as may be profitable to the salvation of my soul.",
      "Grant me, I beseech Thee, to receive not only the Sacrament of the Body and Blood of the Lord, but also the grace and power of the Sacrament. O most gentle God, grant me so to receive the Body of Thine only-begotten Son, which He took of the Virgin Mary, that I may be incorporated into His mystical Body and numbered among His members.",
      "O most loving Father, grant that I may at last behold for ever face to face Thy beloved Son, whom now I purpose to receive beneath the sacramental veil. Who liveth and reigneth with Thee in the unity of the Holy Ghost, God, world without end. Amen.",
    ],
  },
  {
    slug: "adoro-te-devote",
    title: "Hidden Godhead, Devoutly I Adore Thee",
    category: "Eucharistic",
    form: "Hymn",
    latinTitle: "Adoro Te Devote",
    keywords: ["eucharist", "adoration", "saint thomas aquinas", "hymn", "real presence"],
    summary: "Adore Christ hidden beneath the sacramental veils and ask for deeper faith, hope, and love.",
    whenToPray: "During Eucharistic adoration or after Holy Communion",
    source: "Medieval Eucharistic hymn attributed to Saint Thomas Aquinas; public-domain English verse",
    text: [
      "Hidden Godhead, devoutly I adore Thee, who truly art hidden beneath these appearances. My whole heart submits itself to Thee, for in contemplating Thee it is wholly lost.",
      "Sight, touch, and taste are all deceived in their judgment of Thee; but hearing suffices firmly to believe. I believe all that the Son of God hath spoken; there is nothing truer than this word of Truth.",
      "On the Cross only Thy divinity was hidden; but here Thy humanity also is hidden. Yet believing and confessing both, I ask for what the penitent thief asked.",
      "I do not see Thy wounds as Thomas saw them; yet I confess Thee to be my God. Make me believe Thee ever more and more, hope in Thee, and love Thee.",
      "O memorial of the death of the Lord, living Bread giving life to man, grant my soul to live by Thee, and ever to taste Thy sweetness.",
      "O loving Pelican, Lord Jesus, cleanse me, unclean, in Thy Blood, one drop of which can save the whole world from all its sin.",
      "Jesus, whom now I see hidden, I pray Thee, fulfill my longing: that, seeing Thy face unveiled, I may be happy in the vision of Thy glory. Amen.",
    ],
  },
  {
    slug: "o-salutaris-hostia",
    title: "O Saving Victim",
    category: "Eucharistic",
    form: "Hymn",
    latinTitle: "O Salutaris Hostia",
    keywords: ["eucharist", "benediction", "adoration", "hymn", "saving victim"],
    summary: "Honor Christ, the saving Victim who opens heaven and strengthens His people.",
    whenToPray: "At exposition or Benediction of the Blessed Sacrament",
    source: "Saint Thomas Aquinas, Verbum Supernum; public-domain English verse",
    text: [
      "O saving Victim, opening wide the gate of heaven to man below! Our foes press on from every side; Thine aid supply, Thy strength bestow.",
      "To Thy great name be endless praise, immortal Godhead, One in Three; O grant us endless length of days in our true native land with Thee. Amen.",
    ],
  },
  {
    slug: "tantum-ergo",
    title: "Down in Adoration Falling",
    category: "Eucharistic",
    form: "Hymn",
    latinTitle: "Tantum Ergo Sacramentum",
    keywords: ["eucharist", "benediction", "adoration", "hymn", "saint thomas aquinas"],
    summary: "Adore the Blessed Sacrament with faith beyond the reach of the senses.",
    whenToPray: "At Benediction or during Eucharistic adoration",
    source: "Saint Thomas Aquinas, Pange Lingua; Edward Caswall public-domain translation",
    text: [
      "Down in adoration falling, lo! the sacred Host we hail; lo! o'er ancient forms departing, newer rites of grace prevail; faith for all defects supplying, where the feeble senses fail.",
      "To the everlasting Father, and the Son who reigns on high, with the Holy Ghost proceeding forth from each eternally, be salvation, honor, blessing, might, and endless majesty. Amen.",
      "V. Thou hast given them bread from heaven. R. Having in itself all delight.",
      "Let us pray. O God, who in this wonderful Sacrament hast left us a memorial of Thy Passion, grant us, we beseech Thee, so to venerate the sacred mysteries of Thy Body and Blood that we may ever feel within ourselves the fruit of Thy redemption. Who livest and reignest, world without end. Amen.",
    ],
  },
  {
    slug: "prayer-after-communion-aquinas",
    title: "Thanksgiving After Holy Communion",
    category: "Eucharistic",
    form: "Prayer",
    latinTitle: "Gratias Tibi Ago, Domine Sancte",
    keywords: ["communion", "thanksgiving", "saint thomas aquinas", "eucharist", "virtue"],
    summary: "Thank God for Holy Communion and ask that the Sacrament bear lasting fruit.",
    whenToPray: "Immediately after receiving Holy Communion",
    source: "Traditional prayer of Saint Thomas Aquinas; public-domain English form",
    text: [
      "I give Thee thanks, O Lord, holy Father, almighty and everlasting God, who hast vouchsafed, not for any merit of mine, but only through the condescension of Thy mercy, to feed me, a sinner, Thine unworthy servant, with the precious Body and Blood of Thy Son, our Lord Jesus Christ.",
      "I pray that this Holy Communion be not to me a condemnation unto punishment, but a saving intercession unto pardon. May it be to me the armor of faith and the shield of good will. May it avail to deliver me from all my vices; to destroy in me all evil desires; to increase in me charity and patience, humility and obedience, and every virtue.",
      "May it be a firm defense against the snares of all my enemies, seen and unseen; may it perfectly quiet all movements of sin in my flesh and spirit; may it bind me firmly to Thee, the one true God; and may it bring my last hour to a happy close.",
      "And I pray Thee to lead me, a sinner, to that heavenly banquet where Thou, with Thy Son and the Holy Ghost, art to Thy saints true light, full contentment, everlasting joy, delight unfailing, and perfect happiness. Through the same Christ our Lord. Amen.",
    ],
  },
  {
    slug: "act-of-perfect-contrition",
    title: "Act of Perfect Contrition",
    category: "Reconciliation",
    form: "Prayer",
    latinTitle: "Actus Contritionis Perfectae",
    keywords: ["contrition", "forgiveness", "confession", "repentance", "amendment"],
    summary: "Repent chiefly because sin offends God, who is infinitely good and worthy of love.",
    whenToPray: "After grave sin, during an examen, or while preparing for Confession",
    source: "Traditional Catholic act; public-domain English form",
    text: [
      "O my God, I am sorry and beg pardon for all my sins, not only because I have deserved the punishments which Thou hast justly appointed for sin, but especially because I have offended Thee, the highest and most lovable Good.",
      "I detest all my sins and firmly resolve, by the help of Thy grace, to sin no more, to avoid the near occasions of sin, and to confess my sins as soon as I am able. Amen.",
    ],
  },
  {
    slug: "consecration-to-sacred-heart",
    title: "Consecration to the Sacred Heart of Jesus",
    category: "Christ & Trinity",
    form: "Consecration",
    latinTitle: "Consecratio Sacratissimo Cordi Iesu",
    keywords: ["sacred heart", "consecration", "Jesus", "trust", "first friday"],
    summary: "Give the whole self to the loving Heart of Christ and place every hope in Him.",
    whenToPray: "On First Fridays, in June, or when renewing personal consecration",
    source: "Traditional personal consecration associated with Saint Margaret Mary; public-domain English form",
    text: [
      "Most sweet Jesus, I consecrate to Thy Sacred Heart myself and all that I have, so that every part of my being may honor, love, and glorify Thee. This is my irrevocable will: to be wholly Thine and to do all things for love of Thee, renouncing with my whole heart whatever is displeasing to Thee.",
      "I take Thee, O Sacred Heart, as the sole object of my love, the protector of my life, the pledge of my salvation, the remedy of my weakness and inconstancy, the atonement for all the faults of my life, and my sure refuge at the hour of death.",
      "Be Thou, O Heart of goodness, my justification before God the Father, and turn away from me the punishment which my sins deserve. O Heart of love, I place all my trust in Thee; for I fear all things from my own weakness, but I hope for all things from Thy goodness.",
      "Destroy in me all that can displease or resist Thee. Imprint Thy pure love so deeply in my heart that I may never forget Thee or be separated from Thee. May my name be written in Thy Heart, for I desire to place all my happiness and all my glory in living and dying as Thy devoted servant. Amen.",
    ],
  },
  {
    slug: "litany-holy-name",
    title: "Litany of the Holy Name of Jesus",
    category: "Litanies",
    form: "Litany",
    latinTitle: "Litaniae Sanctissimi Nominis Iesu",
    keywords: ["litany", "holy name", "jesus", "january", "deliverance"],
    summary: "Honor the saving Name of Jesus and invoke every mystery of His life.",
    whenToPray: "In January, in temptation, or in devotion to the Holy Name",
    source: "Historic approved litany; traditional public-domain English form",
    text: [
      "Lord, have mercy on us. Christ, have mercy on us. Lord, have mercy on us. Jesus, hear us. Jesus, graciously hear us.",
      "God the Father of heaven, have mercy on us. God the Son, Redeemer of the world, have mercy on us. God the Holy Ghost, have mercy on us. Holy Trinity, one God, have mercy on us.",
      "Jesus, Son of the living God, have mercy on us. Jesus, splendor of the Father, have mercy on us. Jesus, brightness of eternal light, have mercy on us. Jesus, King of glory, have mercy on us. Jesus, Sun of justice, have mercy on us.",
      "Jesus, Son of the Virgin Mary, have mercy on us. Jesus most amiable, have mercy on us. Jesus most admirable, have mercy on us. Jesus, mighty God, have mercy on us. Jesus, Father of the world to come, have mercy on us. Jesus, Angel of great counsel, have mercy on us.",
      "Jesus most powerful, have mercy on us. Jesus most patient, have mercy on us. Jesus most obedient, have mercy on us. Jesus, meek and humble of heart, have mercy on us. Jesus, lover of chastity, have mercy on us. Jesus, lover of us, have mercy on us.",
      "Jesus, God of peace, have mercy on us. Jesus, Author of life, have mercy on us. Jesus, model of virtues, have mercy on us. Jesus, zealous lover of souls, have mercy on us. Jesus, our God, have mercy on us. Jesus, our refuge, have mercy on us.",
      "Jesus, Father of the poor, have mercy on us. Jesus, treasure of the faithful, have mercy on us. Jesus, good Shepherd, have mercy on us. Jesus, true Light, have mercy on us. Jesus, eternal Wisdom, have mercy on us. Jesus, infinite Goodness, have mercy on us.",
      "Jesus, our way and our life, have mercy on us. Jesus, joy of Angels, have mercy on us. Jesus, King of Patriarchs, have mercy on us. Jesus, Master of Apostles, have mercy on us. Jesus, Teacher of Evangelists, have mercy on us. Jesus, strength of Martyrs, have mercy on us.",
      "Jesus, light of Confessors, have mercy on us. Jesus, purity of Virgins, have mercy on us. Jesus, crown of all Saints, have mercy on us.",
      "Be merciful, spare us, O Jesus. Be merciful, graciously hear us, O Jesus.",
      "From all evil, deliver us, O Jesus. From all sin, deliver us, O Jesus. From Thy wrath, deliver us, O Jesus. From the snares of the devil, deliver us, O Jesus. From the spirit of uncleanness, deliver us, O Jesus. From everlasting death, deliver us, O Jesus. From neglect of Thy holy inspirations, deliver us, O Jesus.",
      "By the mystery of Thy holy Incarnation, deliver us, O Jesus. By Thy Nativity, deliver us, O Jesus. By Thine infancy, deliver us, O Jesus. By Thy most divine life, deliver us, O Jesus. By Thy labors, deliver us, O Jesus. By Thine agony and Passion, deliver us, O Jesus.",
      "By Thy Cross and dereliction, deliver us, O Jesus. By Thy faintness and weariness, deliver us, O Jesus. By Thy death and burial, deliver us, O Jesus. By Thy Resurrection, deliver us, O Jesus. By Thine Ascension, deliver us, O Jesus. By Thine institution of the most Holy Eucharist, deliver us, O Jesus. By Thy joys, deliver us, O Jesus. By Thy glory, deliver us, O Jesus.",
      "Lamb of God, who takest away the sins of the world, spare us, O Jesus. Lamb of God, who takest away the sins of the world, graciously hear us, O Jesus. Lamb of God, who takest away the sins of the world, have mercy on us, O Jesus.",
      "Jesus, hear us. Jesus, graciously hear us.",
      "Let us pray. O Lord Jesus Christ, who hast said: Ask, and ye shall receive; seek, and ye shall find; knock, and it shall be opened unto you; mercifully attend to our supplications, and grant us the gift of Thy divine charity, that we may ever love Thee with our whole heart, and may never cease from praising Thee. Make us, O Lord, to have a perpetual fear and love of Thy holy Name; for Thou never failest to govern those whom Thou dost solidly establish in Thy love. Who livest and reignest for ever and ever. Amen.",
    ],
  },
  {
    slug: "litany-sacred-heart",
    title: "Litany of the Sacred Heart of Jesus",
    category: "Litanies",
    form: "Litany",
    latinTitle: "Litaniae Sacratissimi Cordis Iesu",
    keywords: ["litany", "sacred heart", "jesus", "first friday", "june"],
    summary: "Contemplate the Heart of Christ as the fountain of charity, mercy, and life.",
    whenToPray: "On First Fridays, in June, or during Eucharistic adoration",
    source: "Historic approved litany; traditional public-domain English form",
    text: [
      "Lord, have mercy on us. Christ, have mercy on us. Lord, have mercy on us. Christ, hear us. Christ, graciously hear us.",
      "God the Father of heaven, have mercy on us. God the Son, Redeemer of the world, have mercy on us. God the Holy Ghost, have mercy on us. Holy Trinity, one God, have mercy on us.",
      "Heart of Jesus, Son of the Eternal Father, have mercy on us. Heart of Jesus, formed by the Holy Ghost in the womb of the Virgin Mother, have mercy on us. Heart of Jesus, substantially united to the Word of God, have mercy on us.",
      "Heart of Jesus, of infinite majesty, have mercy on us. Heart of Jesus, holy temple of God, have mercy on us. Heart of Jesus, tabernacle of the Most High, have mercy on us. Heart of Jesus, house of God and gate of heaven, have mercy on us.",
      "Heart of Jesus, glowing furnace of charity, have mercy on us. Heart of Jesus, abode of justice and love, have mercy on us. Heart of Jesus, full of goodness and love, have mercy on us. Heart of Jesus, abyss of all virtues, have mercy on us.",
      "Heart of Jesus, most worthy of all praise, have mercy on us. Heart of Jesus, King and center of all hearts, have mercy on us. Heart of Jesus, in whom are all the treasures of wisdom and knowledge, have mercy on us. Heart of Jesus, in whom dwelleth all the fullness of the Godhead, have mercy on us.",
      "Heart of Jesus, in whom the Father was well pleased, have mercy on us. Heart of Jesus, of whose fullness we have all received, have mercy on us. Heart of Jesus, desire of the everlasting hills, have mercy on us. Heart of Jesus, patient and rich in mercy, have mercy on us.",
      "Heart of Jesus, rich unto all who call upon Thee, have mercy on us. Heart of Jesus, fountain of life and holiness, have mercy on us. Heart of Jesus, propitiation for our sins, have mercy on us. Heart of Jesus, loaded down with opprobrium, have mercy on us.",
      "Heart of Jesus, bruised for our offenses, have mercy on us. Heart of Jesus, made obedient unto death, have mercy on us. Heart of Jesus, pierced with a lance, have mercy on us. Heart of Jesus, source of all consolation, have mercy on us.",
      "Heart of Jesus, our life and resurrection, have mercy on us. Heart of Jesus, our peace and reconciliation, have mercy on us. Heart of Jesus, victim for our sins, have mercy on us. Heart of Jesus, salvation of those who trust in Thee, have mercy on us.",
      "Heart of Jesus, hope of those who die in Thee, have mercy on us. Heart of Jesus, delight of all Saints, have mercy on us.",
      "Lamb of God, who takest away the sins of the world, spare us, O Lord. Lamb of God, who takest away the sins of the world, graciously hear us, O Lord. Lamb of God, who takest away the sins of the world, have mercy on us.",
      "V. Jesus, meek and humble of heart. R. Make our hearts like unto Thine.",
      "Let us pray. Almighty and everlasting God, look upon the Heart of Thy well-beloved Son and upon the praise and satisfaction which He offers Thee in the name of sinners; and do Thou, of Thy great goodness, grant them pardon when they seek Thy mercy, in the name of the same Jesus Christ, Thy Son, who liveth and reigneth with Thee, world without end. Amen.",
    ],
  },
  {
    slug: "litany-precious-blood",
    title: "Litany of the Most Precious Blood",
    category: "Litanies",
    form: "Litany",
    latinTitle: "Litaniae Pretiosissimi Sanguinis",
    keywords: ["litany", "precious blood", "jesus", "redemption", "july"],
    summary: "Praise the Blood of Christ poured out for redemption, mercy, and eternal life.",
    whenToPray: "In July, on Fridays, or in prayer for redemption and mercy",
    source: "Historic approved Latin litany; literal traditional public-domain English form",
    text: [
      "Lord, have mercy on us. Christ, have mercy on us. Lord, have mercy on us. Christ, hear us. Christ, graciously hear us.",
      "God the Father of heaven, have mercy on us. God the Son, Redeemer of the world, have mercy on us. God the Holy Ghost, have mercy on us. Holy Trinity, one God, have mercy on us.",
      "Blood of Christ, only-begotten Son of the Eternal Father, save us. Blood of Christ, Incarnate Word of God, save us. Blood of Christ, of the new and eternal testament, save us.",
      "Blood of Christ, falling upon the earth in the Agony, save us. Blood of Christ, shed profusely in the Scourging, save us. Blood of Christ, flowing forth in the Crowning with Thorns, save us. Blood of Christ, poured out upon the Cross, save us.",
      "Blood of Christ, price of our salvation, save us. Blood of Christ, without which there is no forgiveness, save us. Blood of Christ, Eucharistic drink and refreshment of souls, save us. Blood of Christ, stream of mercy, save us.",
      "Blood of Christ, victor over demons, save us. Blood of Christ, courage of Martyrs, save us. Blood of Christ, strength of Confessors, save us. Blood of Christ, bringing forth Virgins, save us.",
      "Blood of Christ, help of those in peril, save us. Blood of Christ, relief of the burdened, save us. Blood of Christ, solace in sorrow, save us. Blood of Christ, hope of the penitent, save us.",
      "Blood of Christ, consolation of the dying, save us. Blood of Christ, peace and tenderness of hearts, save us. Blood of Christ, pledge of eternal life, save us. Blood of Christ, freeing souls from purgatory, save us. Blood of Christ, most worthy of all glory and honor, save us.",
      "Lamb of God, who takest away the sins of the world, spare us, O Lord. Lamb of God, who takest away the sins of the world, graciously hear us, O Lord. Lamb of God, who takest away the sins of the world, have mercy on us.",
      "V. Thou hast redeemed us, O Lord, in Thy Blood. R. And made us a kingdom for our God.",
      "Let us pray. Almighty and everlasting God, Thou hast appointed Thine only-begotten Son the Redeemer of the world and hast willed to be appeased by His Blood. Grant us, we beseech Thee, so to venerate the price of our salvation and by its power to be defended from the evils of this present life, that we may rejoice in its fruit for ever in heaven. Through the same Christ our Lord. Amen.",
    ],
  },
  {
    slug: "litany-loreto",
    title: "Litany of the Blessed Virgin Mary",
    category: "Litanies",
    form: "Litany",
    latinTitle: "Litaniae Lauretanae",
    keywords: ["litany", "loreto", "mary", "blessed virgin", "rosary"],
    summary: "Invoke the Mother of God under the venerable titles of the Litany of Loreto.",
    whenToPray: "On Marian feasts, Saturdays, or after the Rosary",
    source: "Litany of Loreto, including the current approved invocations; traditional English rendering",
    text: [
      "Lord, have mercy on us. Christ, have mercy on us. Lord, have mercy on us. Christ, hear us. Christ, graciously hear us.",
      "God the Father of heaven, have mercy on us. God the Son, Redeemer of the world, have mercy on us. God the Holy Ghost, have mercy on us. Holy Trinity, one God, have mercy on us.",
      "Holy Mary, pray for us. Holy Mother of God, pray for us. Holy Virgin of virgins, pray for us.",
      "Mother of Christ, pray for us. Mother of the Church, pray for us. Mother of mercy, pray for us. Mother of divine grace, pray for us. Mother of hope, pray for us. Mother most pure, pray for us. Mother most chaste, pray for us. Mother inviolate, pray for us. Mother undefiled, pray for us.",
      "Mother most amiable, pray for us. Mother most admirable, pray for us. Mother of good counsel, pray for us. Mother of our Creator, pray for us. Mother of our Saviour, pray for us.",
      "Virgin most prudent, pray for us. Virgin most venerable, pray for us. Virgin most renowned, pray for us. Virgin most powerful, pray for us. Virgin most merciful, pray for us. Virgin most faithful, pray for us.",
      "Mirror of justice, pray for us. Seat of wisdom, pray for us. Cause of our joy, pray for us. Spiritual vessel, pray for us. Vessel of honor, pray for us. Singular vessel of devotion, pray for us.",
      "Mystical rose, pray for us. Tower of David, pray for us. Tower of ivory, pray for us. House of gold, pray for us. Ark of the covenant, pray for us. Gate of heaven, pray for us. Morning star, pray for us.",
      "Health of the sick, pray for us. Refuge of sinners, pray for us. Solace of migrants, pray for us. Comfort of the afflicted, pray for us. Help of Christians, pray for us.",
      "Queen of Angels, pray for us. Queen of Patriarchs, pray for us. Queen of Prophets, pray for us. Queen of Apostles, pray for us. Queen of Martyrs, pray for us. Queen of Confessors, pray for us. Queen of Virgins, pray for us. Queen of all Saints, pray for us.",
      "Queen conceived without original sin, pray for us. Queen assumed into heaven, pray for us. Queen of the most holy Rosary, pray for us. Queen of families, pray for us. Queen of peace, pray for us.",
      "Lamb of God, who takest away the sins of the world, spare us, O Lord. Lamb of God, who takest away the sins of the world, graciously hear us, O Lord. Lamb of God, who takest away the sins of the world, have mercy on us.",
      "V. Pray for us, O holy Mother of God. R. That we may be made worthy of the promises of Christ.",
      "Let us pray. Grant, we beseech Thee, O Lord God, that we Thy servants may enjoy perpetual health of mind and body; and by the glorious intercession of blessed Mary ever Virgin may be delivered from present sorrow and come to eternal joy. Through Christ our Lord. Amen.",
    ],
  },
  {
    slug: "litany-saint-joseph",
    title: "Litany of Saint Joseph",
    category: "Litanies",
    form: "Litany",
    latinTitle: "Litaniae Sancti Ioseph",
    keywords: ["litany", "saint joseph", "holy family", "workers", "dying"],
    summary: "Invoke Saint Joseph as guardian of Christ, model of workers, and patron of the dying.",
    whenToPray: "On Wednesdays, in March, or for family, work, and a holy death",
    source: "Approved Litany of Saint Joseph, including the seven invocations added in 2021; traditional English rendering",
    text: [
      "Lord, have mercy on us. Christ, have mercy on us. Lord, have mercy on us. Christ, hear us. Christ, graciously hear us.",
      "God the Father of heaven, have mercy on us. God the Son, Redeemer of the world, have mercy on us. God the Holy Ghost, have mercy on us. Holy Trinity, one God, have mercy on us.",
      "Holy Mary, pray for us. Saint Joseph, pray for us. Renowned offspring of David, pray for us. Light of Patriarchs, pray for us.",
      "Spouse of the Mother of God, pray for us. Guardian of the Redeemer, pray for us. Chaste guardian of the Virgin, pray for us. Foster-father of the Son of God, pray for us. Diligent protector of Christ, pray for us. Servant of Christ, pray for us. Minister of salvation, pray for us. Head of the Holy Family, pray for us.",
      "Joseph most just, pray for us. Joseph most chaste, pray for us. Joseph most prudent, pray for us. Joseph most strong, pray for us. Joseph most obedient, pray for us. Joseph most faithful, pray for us.",
      "Mirror of patience, pray for us. Lover of poverty, pray for us. Model of workmen, pray for us. Glory of home life, pray for us. Guardian of virgins, pray for us. Pillar of families, pray for us. Support in difficulties, pray for us.",
      "Solace of the afflicted, pray for us. Hope of the sick, pray for us. Patron of exiles, pray for us. Patron of the afflicted, pray for us. Patron of the poor, pray for us. Patron of the dying, pray for us. Terror of demons, pray for us. Protector of Holy Church, pray for us.",
      "Lamb of God, who takest away the sins of the world, spare us, O Lord. Lamb of God, who takest away the sins of the world, graciously hear us, O Lord. Lamb of God, who takest away the sins of the world, have mercy on us.",
      "V. He made him the lord of His household. R. And ruler over all His possessions.",
      "Let us pray. O God, who in Thine ineffable providence didst vouchsafe to choose blessed Joseph to be the spouse of Thy most holy Mother, grant, we beseech Thee, that we may have him for an intercessor in heaven whom we venerate as our protector on earth. Who livest and reignest, world without end. Amen.",
    ],
  },
  {
    slug: "litany-all-saints",
    title: "Litany of All Saints",
    category: "Litanies",
    form: "Litany",
    latinTitle: "Litaniae Sanctorum",
    keywords: ["litany", "all saints", "rogation", "intercession", "church"],
    summary: "Call upon the whole court of heaven and plead for deliverance, holiness, and peace.",
    whenToPray: "On All Saints, Rogation days, vigils, or in great need",
    source: "Ancient Roman litany; historic public-domain English form",
    text: [
      "Lord, have mercy on us. Christ, have mercy on us. Lord, have mercy on us. Christ, hear us. Christ, graciously hear us.",
      "God the Father of heaven, have mercy on us. God the Son, Redeemer of the world, have mercy on us. God the Holy Ghost, have mercy on us. Holy Trinity, one God, have mercy on us.",
      "Holy Mary, pray for us. Holy Mother of God, pray for us. Holy Virgin of virgins, pray for us.",
      "Saint Michael, pray for us. Saint Gabriel, pray for us. Saint Raphael, pray for us. All ye holy Angels and Archangels, pray for us. All ye holy orders of blessed spirits, pray for us.",
      "Saint John the Baptist, pray for us. Saint Joseph, pray for us. All ye holy Patriarchs and Prophets, pray for us.",
      "Saint Peter, pray for us. Saint Paul, pray for us. Saint Andrew, pray for us. Saint James, pray for us. Saint John, pray for us. Saint Thomas, pray for us. Saint James, pray for us. Saint Philip, pray for us. Saint Bartholomew, pray for us. Saint Matthew, pray for us. Saint Simon, pray for us. Saint Thaddeus, pray for us. Saint Matthias, pray for us. Saint Barnabas, pray for us. Saint Luke, pray for us. Saint Mark, pray for us.",
      "All ye holy Apostles and Evangelists, pray for us. All ye holy Disciples of the Lord, pray for us. All ye holy Innocents, pray for us.",
      "Saint Stephen, pray for us. Saint Lawrence, pray for us. Saint Vincent, pray for us. Saints Fabian and Sebastian, pray for us. Saints John and Paul, pray for us. Saints Cosmas and Damian, pray for us. Saints Gervase and Protase, pray for us. All ye holy Martyrs, pray for us.",
      "Saint Sylvester, pray for us. Saint Gregory, pray for us. Saint Ambrose, pray for us. Saint Augustine, pray for us. Saint Jerome, pray for us. Saint Martin, pray for us. Saint Nicholas, pray for us. All ye holy Bishops and Confessors, pray for us. All ye holy Doctors, pray for us.",
      "Saint Anthony, pray for us. Saint Benedict, pray for us. Saint Bernard, pray for us. Saint Dominic, pray for us. Saint Francis, pray for us. All ye holy Priests and Levites, pray for us. All ye holy Monks and Hermits, pray for us.",
      "Saint Mary Magdalene, pray for us. Saint Agatha, pray for us. Saint Lucy, pray for us. Saint Agnes, pray for us. Saint Cecilia, pray for us. Saint Catherine, pray for us. Saint Anastasia, pray for us. All ye holy Virgins and Widows, pray for us. All ye Saints of God, intercede for us.",
      "Be merciful, spare us, O Lord. Be merciful, graciously hear us, O Lord.",
      "From all evil, deliver us, O Lord. From all sin, deliver us, O Lord. From Thy wrath, deliver us, O Lord. From a sudden and unprovided death, deliver us, O Lord. From the snares of the devil, deliver us, O Lord. From anger, hatred, and all ill will, deliver us, O Lord. From the spirit of uncleanness, deliver us, O Lord. From lightning and tempest, deliver us, O Lord. From the scourge of earthquake, deliver us, O Lord. From plague, famine, and war, deliver us, O Lord. From everlasting death, deliver us, O Lord.",
      "Through the mystery of Thy holy Incarnation, deliver us, O Lord. Through Thy coming, deliver us, O Lord. Through Thy Nativity, deliver us, O Lord. Through Thy Baptism and holy fasting, deliver us, O Lord. Through Thy Cross and Passion, deliver us, O Lord. Through Thy death and burial, deliver us, O Lord. Through Thy holy Resurrection, deliver us, O Lord. Through Thine admirable Ascension, deliver us, O Lord. Through the coming of the Holy Ghost the Comforter, deliver us, O Lord. In the day of judgment, deliver us, O Lord.",
      "We sinners, we beseech Thee, hear us. That Thou wouldst spare us, we beseech Thee, hear us. That Thou wouldst pardon us, we beseech Thee, hear us. That Thou wouldst bring us to true penance, we beseech Thee, hear us.",
      "That Thou wouldst vouchsafe to govern and preserve Thy holy Church, we beseech Thee, hear us. That Thou wouldst preserve our Apostolic Prelate and all ecclesiastical orders in holy religion, we beseech Thee, hear us. That Thou wouldst humble the enemies of Holy Church, we beseech Thee, hear us.",
      "That Thou wouldst give peace and true concord to Christian rulers, we beseech Thee, hear us. That Thou wouldst give peace and unity to all Christian people, we beseech Thee, hear us. That Thou wouldst restore to the unity of the Church all who have strayed and lead all unbelievers to the light of the Gospel, we beseech Thee, hear us.",
      "That Thou wouldst confirm and preserve us in Thy holy service, we beseech Thee, hear us. That Thou wouldst lift up our minds to heavenly desires, we beseech Thee, hear us. That Thou wouldst render eternal blessings to all our benefactors, we beseech Thee, hear us.",
      "That Thou wouldst deliver our souls and the souls of our brethren, relations, and benefactors from eternal damnation, we beseech Thee, hear us. That Thou wouldst give and preserve the fruits of the earth, we beseech Thee, hear us. That Thou wouldst give eternal rest to all the faithful departed, we beseech Thee, hear us.",
      "That Thou wouldst vouchsafe graciously to hear us, we beseech Thee, hear us. Son of God, we beseech Thee, hear us.",
      "Lamb of God, who takest away the sins of the world, spare us, O Lord. Lamb of God, who takest away the sins of the world, graciously hear us, O Lord. Lamb of God, who takest away the sins of the world, have mercy on us.",
      "Christ, hear us. Christ, graciously hear us. Lord, have mercy on us. Christ, have mercy on us. Lord, have mercy on us.",
      "Let us pray. O God, whose property is always to have mercy and to spare, receive our petition, that we and all Thy servants who are bound by the chain of sin may, by the compassion of Thy goodness, mercifully be absolved. Hear, we beseech Thee, O Lord, the prayers of Thy suppliants, and pardon the sins of those who confess to Thee, that in Thy bounty Thou mayest grant us both pardon and peace. Through Christ our Lord. Amen.",
    ],
  },
];

export const treasuryGuides: DevotionGuide[] = [
  {
    slug: "novena-to-the-holy-ghost",
    title: "Novena to the Holy Ghost",
    category: "Novena",
    eyebrow: "Nine days before Pentecost",
    summary: "Ask the Holy Ghost to deepen His seven gifts and bring forth holy fruit in the soul.",
    duration: "Nine days · 12-18 minutes daily",
    provenance:
      "Traditional Pentecost novena pattern using public-domain hymns and prayers.",
    pastoralNote:
      "Begin on the Friday after Ascension Thursday when following the oldest nine-day pattern, or pray during any nine days of need.",
    steps: [
      {
        title: "The common opening for every day",
        instruction:
          "Make the Sign of the Cross. Pray: Come, Holy Ghost, fill the hearts of Thy faithful and kindle in them the fire of Thy love. V. Send forth Thy Spirit and they shall be created. R. And Thou shalt renew the face of the earth. Then pray the Veni Creator Spiritus from this treasury.",
      },
      {
        title: "Day 1 · Desire for the Holy Ghost",
        instruction:
          "O Holy Ghost, Lord of light, descend upon me and banish the darkness of sin and error. Make me attentive to Thy inspirations and wholly ready for Thy service. Grant that I may desire Thee above every passing consolation. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "John 14:16-17",
      },
      {
        title: "Day 2 · Holy fear",
        instruction:
          "Come, Spirit of holy fear. Penetrate my inmost heart, that I may set Thee, my Lord and God, before my face for ever; shun all that can offend Thee; and serve Thee with a pure conscience. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "Proverbs 9:10",
      },
      {
        title: "Day 3 · Piety",
        instruction:
          "Come, Spirit of piety. Possess my heart and incline it toward God with filial love, toward His Church with devotion, and toward every person with patient charity. Make the duties of religion my delight. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "Romans 8:14-16",
      },
      {
        title: "Day 4 · Fortitude",
        instruction:
          "Come, Spirit of fortitude. Strengthen my soul in trouble and adversity; sustain every effort after holiness; and grant me courage to bear my cross and confess the faith without human respect. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "2 Timothy 1:7-8",
      },
      {
        title: "Day 5 · Knowledge",
        instruction:
          "Come, Spirit of knowledge. Grant that I may see created things according to their true worth, use them for Thy glory, and never prefer the gift to the Giver. Show me the path appointed for my salvation. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "Philippians 3:8",
      },
      {
        title: "Day 6 · Understanding",
        instruction:
          "Come, Spirit of understanding. Enlighten my mind to receive the mysteries of salvation with living faith. Give me a faithful love of sacred Scripture and the teaching of the Church. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "Luke 24:45",
      },
      {
        title: "Day 7 · Counsel",
        instruction:
          "Come, Spirit of counsel. Direct me in all my ways, that I may choose what is pleasing to God, avoid the snares of the enemy, and guide those entrusted to me with prudence and charity. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "Psalm 31:8",
      },
      {
        title: "Day 8 · Wisdom",
        instruction:
          "Come, Spirit of wisdom. Draw my heart away from disordered attachment and make me taste the things of God. Order all my loves beneath the love of the Most Holy Trinity. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "Wisdom 7:7-10",
      },
      {
        title: "Day 9 · The fruits of the Spirit",
        instruction:
          "Come, divine Spirit. Bring forth in me charity, joy, peace, patience, benignity, goodness, longanimity, mildness, faith, modesty, continency, and chastity. Keep me faithful until these first fruits are perfected in eternal life. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "Galatians 5:22-23",
      },
      {
        title: "The common conclusion for every day",
        instruction:
          "Pray the Prayer for the Seven Gifts from this treasury. Conclude: O God, who didst teach the hearts of Thy faithful by the light of the Holy Ghost, grant us by the same Spirit to have a right judgment in all things and evermore to rejoice in His consolation. Through Christ our Lord. Amen.",
      },
    ],
  },
  {
    slug: "novena-to-the-sacred-heart",
    title: "Novena to the Sacred Heart of Jesus",
    category: "Novena",
    eyebrow: "Nine days of confidence in Christ",
    summary: "Entrust one intention to the merciful Heart of Jesus while growing in faith, reparation, and charity.",
    duration: "Nine days · 10-15 minutes daily",
    provenance:
      "Traditional public-domain Sacred Heart prayers arranged as a nine-day devotion.",
    pastoralNote:
      "A novena is persevering petition, not a guarantee that a particular outcome will occur. Ask confidently while surrendering the manner of the answer to God.",
    steps: [
      {
        title: "The common prayer for every day",
        instruction:
          "Make the Sign of the Cross and name the intention. Pray: O most Sacred Heart of Jesus, fountain of every blessing, I adore Thee, I love Thee, and with lively sorrow for my sins I offer Thee this poor heart of mine. Make me humble, patient, pure, and wholly obedient to Thy will. Grant, good Jesus, that I may live in Thee and for Thee. Protect me in danger, comfort me in affliction, give me health of body, assistance in my temporal needs, Thy blessing on all my works, and the grace of a holy death. Within Thy Heart I place my care. In every need let me come to Thee with humble trust, saying: Heart of Jesus, help me. Amen.",
      },
      {
        title: "Day 1 · The love of the Incarnate Word",
        instruction:
          "Consider the Son of God taking flesh for love of mankind. Ask for wonder before His humility and for grace to answer love with love. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "John 1:14",
      },
      {
        title: "Day 2 · The meek and humble Heart",
        instruction:
          "Bring pride, anger, and impatience before Christ. Ask that thy heart may be made like unto His in meekness and humility. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "Matthew 11:29",
      },
      {
        title: "Day 3 · The Heart obedient unto death",
        instruction:
          "Offer the duties and crosses of thy state in life. Ask for prompt obedience to God's commandments and faithful endurance in trial. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "Philippians 2:8",
      },
      {
        title: "Day 4 · The Heart pierced for sinners",
        instruction:
          "Contemplate the opened side of Christ. Make an honest act of contrition and pray for those most in need of conversion. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "John 19:34",
      },
      {
        title: "Day 5 · The fountain of life and holiness",
        instruction:
          "Ask Jesus to cleanse disordered desires and strengthen every virtue, especially the virtue most needed now. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "John 7:37-38",
      },
      {
        title: "Day 6 · The source of consolation",
        instruction:
          "Place sorrow, fear, and loneliness within the Heart of Christ. Intercede for the afflicted and become willing to console another. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "Matthew 11:28",
      },
      {
        title: "Day 7 · The peace of sinners",
        instruction:
          "Ask for reconciliation with God and neighbor. Forgive from the will, seek pardon where it is owed, and pray for peace in families and nations. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "Ephesians 2:13-14",
      },
      {
        title: "Day 8 · The Eucharistic Heart",
        instruction:
          "Adore Christ's abiding gift of Himself in the Blessed Sacrament. Ask for worthy Communion, grateful thanksgiving, and love for the Mass. Pray one Our Father, one Hail Mary, and one Glory Be.",
        scripture: "John 6:51",
      },
      {
        title: "Day 9 · Confidence and consecration",
        instruction:
          "Surrender the novena intention to divine wisdom. Pray the Consecration to the Sacred Heart and repeat slowly three times: Sacred Heart of Jesus, I place my trust in Thee.",
        scripture: "Romans 8:32",
      },
      {
        title: "The common conclusion",
        instruction:
          "Pray: V. Jesus, meek and humble of heart. R. Make our hearts like unto Thine. Almighty and everlasting God, look upon the Heart of Thy well-beloved Son and upon the praise and satisfaction which He offers Thee in the name of sinners; and grant pardon to those who seek Thy mercy, through the same Christ our Lord. Amen.",
      },
    ],
  },
  {
    slug: "first-friday-sacred-heart",
    title: "The First Friday Devotion",
    category: "Eucharistic devotion",
    eyebrow: "Communion, reparation, and love",
    summary: "Keep the first Friday of the month close to the Sacred Heart through Mass, Communion, reparation, and thanksgiving.",
    duration: "At Mass plus 15-30 minutes of personal prayer",
    provenance:
      "Historic Catholic First Friday practice centered on Mass, Communion, reparation, and thanksgiving.",
    pastoralNote:
      "Holy Communion requires the usual Catholic dispositions. If conscious of grave sin, seek sacramental Confession before receiving; inability to receive does not prevent prayer and adoration.",
    steps: [
      {
        title: "1. Prepare the intention",
        instruction:
          "Before Mass, name the intention: to honor the Sacred Heart of Jesus and make reparation for sin, coldness, and ingratitude. Add the needs of the Church and the conversion of sinners.",
      },
      {
        title: "2. Examine and reconcile",
        instruction:
          "Make a calm examination of conscience. Receive the Sacrament of Penance when needed, forgive injuries from the will, and resolve one concrete amendment of life.",
        scripture: "1 Corinthians 11:28",
      },
      {
        title: "3. Assist at Holy Mass",
        instruction:
          "Unite thyself to Christ's offering to the Father. At the Offertory place thy prayers, works, joys, and sufferings upon the altar; at the Consecration adore in silence.",
      },
      {
        title: "4. Receive or desire Communion",
        instruction:
          "Receive Holy Communion worthily when able. If unable to receive sacramentally, make the Act of Spiritual Communion from the prayer library and remain united to the sacrifice of the Mass.",
      },
      {
        title: "5. Keep thanksgiving",
        instruction:
          "After Communion remain recollected. Pray the Thanksgiving After Holy Communion of Saint Thomas Aquinas, then speak simply to Jesus about gratitude, sorrow, and the grace needed for the coming month.",
      },
      {
        title: "6. Make reparation",
        instruction:
          "Pray the Act of Reparation. Offer one voluntary work of mercy, sacrifice, or patient endurance as a practical expression of love.",
      },
      {
        title: "7. Consecrate the month",
        instruction:
          "Pray the Consecration to the Sacred Heart. Entrust family, duties, weakness, and future trials to Christ, and resolve to return promptly when failure occurs.",
      },
      {
        title: "8. Close with the litany",
        instruction:
          "Pray the Litany of the Sacred Heart. Conclude three times: Sacred Heart of Jesus, I place my trust in Thee. Then make the Sign of the Cross.",
      },
    ],
  },
];
