import type { DevotionGuide, Prayer } from "./prayers";

export const marianSeasonPrayers: Prayer[] = [
  {
    slug: "alma-redemptoris-mater",
    title: "Loving Mother of the Redeemer",
    category: "Marian",
    form: "Antiphon",
    latinTitle: "Alma Redemptoris Mater",
    keywords: ["Advent", "Christmas", "mother", "mercy", "Marian antiphon"],
    summary: "Call upon Mary as the gate of heaven and star of the sea.",
    whenToPray: "From Advent through the season of Christmas, especially at night prayer",
    source: "Ancient Marian antiphon; public-domain English verse by Edward Caswall",
    text: [
      "Mother of Christ! hear thou thy people's cry, Star of the deep, and Portal of the sky!",
      "Mother of Him who thee from nothing made, sinking we strive, and call to thee for aid:",
      "Oh, by that joy which Gabriel brought to thee, thou Virgin first and last, let us thy mercy see.",
    ],
  },
  {
    slug: "ave-regina-caelorum",
    title: "Hail, O Queen of Heaven",
    category: "Marian",
    form: "Antiphon",
    latinTitle: "Ave Regina Caelorum",
    keywords: ["Lent", "queen", "heaven", "Marian antiphon"],
    summary: "Greet the Mother of Christ and ask her prayer before her Son.",
    whenToPray: "From the Presentation of the Lord until Holy Thursday, especially at night prayer",
    source: "Medieval Marian antiphon; public-domain English hymn form",
    text: [
      "Hail, O Queen of Heaven enthroned! Hail, by angels Mistress owned! Root of Jesse, Gate of morn, whence the world's true Light was born.",
      "Glorious Virgin, joy to thee, loveliest whom in heaven they see; fairest thou where all are fair, plead with Christ our souls to spare. Amen.",
    ],
  },
  {
    slug: "stabat-mater",
    title: "At the Cross Her Station Keeping",
    category: "Marian",
    form: "Hymn",
    latinTitle: "Stabat Mater Dolorosa",
    keywords: ["sorrows", "Passion", "Cross", "Good Friday", "Stations"],
    summary: "Stand with the sorrowful Mother beneath the Cross of Christ.",
    whenToPray: "During Lent, the Stations of the Cross, or the Memorial of Our Lady of Sorrows",
    source: "Stabat Mater; public-domain English translation by Edward Caswall",
    text: [
      "At the Cross her station keeping, stood the mournful Mother weeping, close to Jesus to the last.",
      "Through her heart, His sorrow sharing, all His bitter anguish bearing, now at length the sword has passed.",
      "O how sad and sore distressed was that Mother, highly blest, of the sole-begotten One.",
      "Christ above in torment hangs; she beneath beholds the pangs of her dying glorious Son.",
      "Is there one who would not weep, whelmed in miseries so deep, Christ's dear Mother to behold?",
      "Can the human heart refrain from partaking in her pain, in that Mother's pain untold?",
      "Bruised, derided, cursed, defiled, she beheld her tender Child all with bloody scourges rent.",
      "For the sins of His own nation, saw Him hang in desolation, till His spirit forth He sent.",
      "O thou Mother! fount of love! Touch my spirit from above, make my heart with thine accord.",
      "Make me feel as thou hast felt; make my soul to glow and melt with the love of Christ my Lord.",
      "Holy Mother! pierce me through; in my heart each wound renew of my Saviour crucified.",
      "Let me share with thee His pain, who for all my sins was slain, who for me in torments died.",
      "Let me mingle tears with thee, mourning Him who mourned for me, all the days that I may live.",
      "By the Cross with thee to stay, there with thee to weep and pray, is all I ask of thee to give.",
      "Virgin of all virgins blest! Listen to my fond request: let me share thy grief divine.",
      "Let me, to my latest breath, in my body bear the death of that dying Son of thine.",
      "Wounded with His every wound, steep my soul till it hath swooned in His very Blood away.",
      "Be to me, O Virgin, nigh, lest in flames I burn and die, in His awful judgment day.",
      "Christ, when Thou shalt call me hence, by Thy Mother my defense, by Thy Cross my victory.",
      "While my body here decays, may my soul Thy goodness praise, safe in Paradise with Thee. Amen.",
    ],
  },
  {
    slug: "consecration-to-mary-de-montfort",
    title: "Consecration to Jesus through Mary",
    category: "Marian",
    form: "Consecration",
    keywords: ["consecration", "baptism", "Jesus", "de Montfort"],
    summary: "Renew the promises of Baptism and give oneself wholly to Jesus through Mary.",
    whenToPray: "On a Marian feast, after preparation for consecration, or when renewing it",
    source: "Saint Louis de Montfort, True Devotion to the Blessed Virgin; traditional English form",
    text: [
      "I, a faithless sinner, renew and ratify today in thy hands the vows of my Baptism; I renounce forever Satan, his pomps and works; and I give myself entirely to Jesus Christ, the Incarnate Wisdom, to carry my cross after Him all the days of my life, and to be more faithful to Him than I have ever been before.",
      "In the presence of all the heavenly court I choose thee this day for my Mother and Mistress. I deliver and consecrate to thee, as thy slave, my body and soul, my goods, both interior and exterior, and even the value of all my good actions, past, present, and future; leaving to thee the entire and full right of disposing of me, and all that belongs to me, without exception, according to thy good pleasure, for the greater glory of God, in time and in eternity. Amen.",
    ],
  },
  {
    slug: "prayer-to-our-lady-of-sorrows",
    title: "Prayer to Our Lady of Sorrows",
    category: "Marian",
    keywords: ["sorrow", "grief", "Passion", "Cross", "petition"],
    summary: "Place sorrow and need within the pierced heart of the Mother who stood by the Cross.",
    whenToPray: "In grief, during Lent, or before meditating on Mary's Seven Sorrows",
    source: "Traditional prayer to Our Lady of Sorrows",
    text: [
      "O most holy and afflicted Virgin, Queen of Martyrs, thou who didst stand motionless beneath the Cross, witnessing the agony of thy expiring Son: through the unceasing sufferings of thy life of sorrow, and the bliss which now more than amply repays thee for thy past trials, look down with a mother's tenderness and pity on me, who kneel before thee to venerate thy dolors, and place my requests, with filial confidence, in the sanctuary of thy wounded heart.",
      "Present them, I beseech thee, on my behalf, to Jesus Christ, through the merits of His own most sacred death and Passion, together with thy sufferings at the foot of the Cross; and through the united efficacy of both obtain the grant of my present petition.",
      "To whom shall I resort in my wants and miseries if not to thee, O Mother of Mercy, who, having so deeply drunk of the chalice of thy Son, canst compassionate the woes of those who still sigh in the land of exile?",
      "Offer for me to my Saviour one drop of the Blood He shed, one pang of the sufferings He endured, one tear of those thou didst shed, and one throb of the grief thou didst feel. O refuge of the universe and hope of the whole world, do not reject my humble petition, but graciously obtain the grant of my requests. Amen.",
    ],
  },
  {
    slug: "our-lady-of-mount-carmel",
    title: "Prayer to Our Lady of Mount Carmel",
    category: "Marian",
    keywords: ["Carmel", "scapular", "need", "mother", "protection"],
    summary: "Seek the maternal help of the Flower of Carmel in a present need.",
    whenToPray: "In a particular need or in devotion to Our Lady of Mount Carmel",
    source: "Traditional Carmelite prayer",
    text: [
      "O most beautiful Flower of Mount Carmel, fruitful vine, splendor of heaven, blessed Mother of the Son of God, Immaculate Virgin, assist me in this my necessity.",
      "O Star of the Sea, help me and show me herein that thou art my Mother. O Holy Mary, Mother of God, Queen of heaven and earth, I humbly beseech thee from the bottom of my heart to succor me in this necessity; there are none that can withstand thy power. O show me herein that thou art my Mother.",
      "O Mary, conceived without sin, pray for us who have recourse to thee. Sweet Mother, I place this cause in thy hands. Amen.",
    ],
  },
  {
    slug: "saint-joseph-after-rosary",
    title: "Prayer to Saint Joseph after the Rosary",
    category: "Saints & angels",
    keywords: ["Joseph", "Rosary", "Church", "family", "protection"],
    summary: "Entrust the Church and every household to Saint Joseph's vigilant care.",
    whenToPray: "After the Rosary or when praying for the Church and family",
    source: "Pope Leo XIII, Quamquam Pluries; traditional English form",
    text: [
      "To thee, O blessed Joseph, we have recourse in our affliction, and having implored the help of thy most holy Spouse, we now, with hearts filled with confidence, earnestly beg thee also to take us under thy protection.",
      "By that charity wherewith thou wert united to the Immaculate Virgin Mother of God, and by that fatherly love with which thou didst cherish the Child Jesus, we beseech thee and humbly pray that thou wilt look down with gracious eye upon that inheritance which Jesus Christ purchased by His Blood, and wilt succor us in our need by thy power and strength.",
      "Defend, O most watchful guardian of the Holy Family, the chosen offspring of Jesus Christ. Keep from us, O most loving father, all blight of error and corruption. Aid us from on high, most valiant defender, in this conflict with the powers of darkness.",
      "And even as of old thou didst rescue the Child Jesus from the peril of His life, so now defend God's holy Church from the snares of the enemy and from all adversity. Shield us ever under thy patronage, that, following thine example and strengthened by thy help, we may live a holy life, die a happy death, and attain to everlasting bliss in heaven. Amen.",
    ],
  },
  {
    slug: "memorare-to-saint-joseph",
    title: "Memorare to Saint Joseph",
    category: "Saints & angels",
    keywords: ["Joseph", "father", "protection", "urgent need"],
    summary: "Approach the foster-father of the Redeemer with filial confidence.",
    whenToPray: "For protection, family needs, work, or a difficult intention",
    source: "Traditional prayer to Saint Joseph",
    text: [
      "Remember, O most pure spouse of the Blessed Virgin Mary, my great protector, Saint Joseph, that no one ever had recourse to thy protection or implored thy aid without obtaining relief.",
      "Confiding therefore in thy goodness, I come before thee and humbly supplicate thee. Despise not my petitions, O foster-father of the Redeemer, but graciously receive them. Amen.",
    ],
  },
  {
    slug: "prayer-to-saint-anne",
    title: "Prayer to Saint Anne",
    category: "Saints & angels",
    keywords: ["Anne", "grandmother", "mother", "family", "intercession"],
    summary: "Ask the mother of the Blessed Virgin Mary for her intercession.",
    whenToPray: "For mothers, grandmothers, families, and growth in holiness",
    source: "Traditional Roman collect for Saint Anne",
    text: [
      "O God, who didst vouchsafe to confer upon blessed Anne such grace that she was found worthy to become the mother of her who brought forth Thine only-begotten Son: mercifully grant that we who celebrate her memory may be helped by her intercession with Thee. Through the same Christ our Lord. Amen.",
    ],
  },
  {
    slug: "prayer-to-saint-joachim",
    title: "Prayer to Saint Joachim",
    category: "Saints & angels",
    keywords: ["Joachim", "grandfather", "father", "family", "intercession"],
    summary: "Seek the patronage of the father of the Blessed Virgin Mary.",
    whenToPray: "For fathers, grandfathers, married couples, and families",
    source: "Traditional Roman collect for Saint Joachim",
    text: [
      "O God, who of all Thy saints didst choose blessed Joachim to be father of the Mother of Thy Son: grant, we beseech Thee, that we may ever be protected by his patronage whose memory we celebrate. Through the same Christ our Lord. Amen.",
    ],
  },
  {
    slug: "prayer-to-saint-anthony",
    title: "Prayer to Saint Anthony of Padua",
    category: "Saints & angels",
    keywords: ["Anthony", "lost", "preaching", "intercession"],
    summary: "Ask that Saint Anthony's intercession strengthen the Church and lead to lasting joy.",
    whenToPray: "When something is lost or when seeking clarity and help",
    source: "Traditional Roman collect for Saint Anthony of Padua",
    text: [
      "May the votive solemnity of blessed Anthony, Thy Confessor, give joy to Thy Church, O God; that she may ever be strengthened by spiritual aid and deserve to possess eternal joys. Through Christ our Lord. Amen.",
    ],
  },
  {
    slug: "prayer-to-saint-jude",
    title: "Prayer to Saint Jude",
    category: "Saints & angels",
    keywords: ["Jude", "hopeless", "despair", "urgent need", "apostle"],
    summary: "Seek the intercession of the Apostle in a cause that appears hopeless.",
    whenToPray: "In grave difficulty or when ordinary help seems exhausted",
    source: "Traditional prayer to Saint Jude Thaddeus",
    text: [
      "O most holy Apostle, Saint Jude, faithful servant and friend of Jesus, the Church honoreth and invoketh thee universally as the patron of hopeless cases and of things almost despaired of. Pray for me, who am so miserable.",
      "Make use, I implore thee, of that particular privilege accorded to thee, to bring visible and speedy help where help was almost despaired of. Come to mine assistance in this great need, that I may receive the consolation and succor of heaven in all my necessities, tribulations, and sufferings, particularly in the intention I now place before God, and that I may praise God with thee and all the elect throughout eternity.",
      "I promise thee, O blessed Jude, to be ever mindful of this great favor, always to honor thee as my special and powerful patron, and gratefully to encourage devotion to thee. Amen.",
    ],
  },
  {
    slug: "prayer-to-saint-therese",
    title: "Prayer to Saint Thérèse of the Child Jesus",
    category: "Saints & angels",
    keywords: ["Therese", "little way", "simplicity", "humility", "Carmelite"],
    summary: "Ask for the humility and simplicity of the Little Way.",
    whenToPray: "When seeking trust, humility, and faithfulness in small things",
    source: "Traditional Roman collect for Saint Thérèse of Lisieux",
    text: [
      "O Lord, who hast said: Unless you become as little children, you shall not enter into the kingdom of heaven; grant unto us, we beseech Thee, so to follow in humility and simplicity of heart the footsteps of blessed Thérèse, that we may obtain everlasting rewards. Who livest and reignest world without end. Amen.",
    ],
  },
  {
    slug: "prayer-to-saint-francis",
    title: "Prayer to Saint Francis of Assisi",
    category: "Saints & angels",
    keywords: ["Francis", "poverty", "creation", "peace", "simplicity"],
    summary: "Ask for detachment and heavenly joy after the example of Saint Francis.",
    whenToPray: "For simplicity, care for creation, peace, or freedom from possessions",
    source: "Traditional Roman collect for Saint Francis of Assisi",
    text: [
      "O God, who through the merits of blessed Francis didst give increase to Thy Church by enriching her with new offspring: grant unto us that, following his example, we may despise earthly goods and ever rejoice in partaking of Thy heavenly gifts. Through Christ our Lord. Amen.",
    ],
  },
  {
    slug: "saint-patricks-breastplate",
    title: "Saint Patrick's Breastplate",
    category: "Saints & angels",
    form: "Hymn",
    latinTitle: "Lorica Sancti Patricii",
    keywords: ["Patrick", "Trinity", "protection", "Christ", "morning"],
    summary: "Bind the whole day to the Holy Trinity and the presence of Christ.",
    whenToPray: "In the morning, before travel, or when asking for protection",
    source: "Ancient Irish lorica; public-domain English verse by Cecil Frances Alexander",
    text: [
      "I bind unto myself today the strong Name of the Trinity, by invocation of the same, the Three in One and One in Three.",
      "I bind this day to me forever, by power of faith, Christ's Incarnation; His baptism in Jordan river; His death on Cross for my salvation; His bursting from the spicèd tomb; His riding up the heavenly way; His coming at the day of doom: I bind unto myself today.",
      "I bind unto myself the power of the great love of Cherubim; the sweet ‘Well done’ in judgment hour; the service of the Seraphim; Confessors' faith, Apostles' word, the Patriarchs' prayers, the Prophets' scrolls; all good deeds done unto the Lord, and purity of virgin souls.",
      "I bind unto myself today the virtues of the starlit heaven, the glorious sun's life-giving ray, the whiteness of the moon at even, the flashing of the lightning free, the whirling wind's tempestuous shocks, the stable earth, the deep salt sea, around the old eternal rocks.",
      "I bind unto myself today the power of God to hold and lead, His eye to watch, His might to stay, His ear to hearken to my need; the wisdom of my God to teach, His hand to guide, His shield to ward; the word of God to give me speech, His heavenly host to be my guard.",
      "Against the demon snares of sin, the vice that gives temptation force, the natural lusts that war within, the hostile men that mar my course; or few or many, far or nigh, in every place and in all hours, against their fierce hostility, I bind to me these holy powers.",
      "Against all Satan's spells and wiles, against false words of heresy, against the knowledge that defiles, against the heart's idolatry, against the wizard's evil craft, against the death-wound and the burning, the choking wave, the poisoned shaft, protect me, Christ, till Thy returning.",
      "Christ be with me, Christ within me, Christ behind me, Christ before me, Christ beside me, Christ to win me, Christ to comfort and restore me. Christ beneath me, Christ above me, Christ in quiet, Christ in danger, Christ in hearts of all that love me, Christ in mouth of friend and stranger.",
      "I bind unto myself the Name, the strong Name of the Trinity; by invocation of the same, the Three in One and One in Three. Of whom all nature hath creation, eternal Father, Spirit, Word: praise to the Lord of my salvation, salvation is of Christ the Lord. Amen.",
    ],
  },
  {
    slug: "prayer-to-saint-gabriel",
    title: "Prayer to Saint Gabriel the Archangel",
    category: "Saints & angels",
    keywords: ["Gabriel", "Annunciation", "messenger", "Incarnation", "angel"],
    summary: "Ask to receive the mystery of the Incarnation with faithful hearts.",
    whenToPray: "On the Annunciation, before sharing the faith, or when seeking courage to answer God",
    source: "Traditional Roman collect for Saint Gabriel the Archangel",
    text: [
      "O God, who from among all Thine Angels didst choose the Archangel Gabriel to announce the mystery of Thine Incarnation: mercifully grant that we who honor him on earth may feel the benefit of his patronage in heaven. Who livest and reignest world without end. Amen.",
    ],
  },
  {
    slug: "prayer-to-saint-monica",
    title: "Prayer to Saint Monica",
    category: "Saints & angels",
    keywords: ["Monica", "Augustine", "children", "conversion", "tears", "parents"],
    summary: "Pray with Saint Monica for conversion, perseverance, and hope for loved ones.",
    whenToPray: "For children, family members, or anyone far from faith",
    source: "Traditional Roman collect for Saint Monica",
    text: [
      "O God, the comforter of them that mourn and the salvation of them that trust in Thee, who didst mercifully accept the loving tears of blessed Monica for the conversion of her son Augustine: grant us, by the united intercession of them both, to bewail our sins and find grace and favor with Thee. Through Christ our Lord. Amen.",
    ],
  },
  {
    slug: "prayer-to-saint-benedict",
    title: "Prayer to Saint Benedict",
    category: "Saints & angels",
    keywords: ["Benedict", "monastic", "work", "prayer", "patronage"],
    summary: "Seek Saint Benedict's patronage for a life ordered toward God.",
    whenToPray: "For stability, disciplined prayer, holy work, and peace",
    source: "Traditional prayer from the Office of Saint Benedict",
    text: [
      "May the intercession of the blessed Abbot Benedict commend us unto Thee, we beseech Thee, O Lord, that what we cannot obtain by our own merits, we may attain through his patronage. Through Christ our Lord. Amen.",
    ],
  },
  {
    slug: "great-o-antiphons",
    title: "The Great O Antiphons",
    category: "Liturgical year",
    form: "Antiphon",
    keywords: ["Advent", "O Antiphons", "Emmanuel", "Wisdom", "December"],
    summary: "Call upon Christ under the seven ancient titles sung before Christmas.",
    whenToPray: "One each day from December 17 through December 23",
    source: "Ancient Roman Advent antiphons; traditional English form",
    text: [
      "December 17 — O Wisdom, who camest forth from the mouth of the Most High, reaching from end to end mightily and ordering all things sweetly: come and teach us the way of prudence.",
      "December 18 — O Adonai and Leader of the house of Israel, who appearedst to Moses in the fire of the burning bush and gavest him the Law on Sinai: come and redeem us with an outstretched arm.",
      "December 19 — O Root of Jesse, who standest for an ensign of the people, before whom kings shall keep silence and unto whom the nations shall make supplication: come to deliver us, and tarry not.",
      "December 20 — O Key of David and Scepter of the house of Israel, who openest and no man shutteth, who shuttest and no man openeth: come and lead forth from prison the captive who sitteth in darkness and in the shadow of death.",
      "December 21 — O Dayspring, Brightness of the everlasting Light and Sun of Justice: come and enlighten them that sit in darkness and in the shadow of death.",
      "December 22 — O King of the nations and their Desired One, the Cornerstone who makest both one: come and save mankind, whom Thou formedst out of clay.",
      "December 23 — O Emmanuel, our King and Lawgiver, the Expectation of the nations and their Saviour: come and save us, O Lord our God.",
    ],
  },
  {
    slug: "saint-andrew-christmas-prayer",
    title: "Saint Andrew Christmas Prayer",
    category: "Liturgical year",
    keywords: ["Advent", "Christmas", "novena", "Andrew", "Bethlehem"],
    summary: "Honor the holy moment of Christ's birth while carrying an Advent intention.",
    whenToPray: "Traditionally from Saint Andrew's Day, November 30, through Christmas Eve",
    source: "Traditional Advent prayer, often called the Saint Andrew Christmas Novena",
    text: [
      "Hail and blessed be the hour and moment in which the Son of God was born of the most pure Virgin Mary, at midnight, in Bethlehem, in piercing cold.",
      "In that hour vouchsafe, I beseech Thee, O my God, to hear my prayer and grant my desires, through the merits of our Saviour Jesus Christ and of His blessed Mother. Amen.",
    ],
  },
  {
    slug: "first-sunday-advent-collect",
    title: "Advent Prayer: Stir Up Thy Power",
    category: "Liturgical year",
    keywords: ["Advent", "coming", "watchfulness", "deliverance"],
    summary: "Ask Christ to come with power and deliver his people from sin.",
    whenToPray: "At the beginning of Advent or whenever longing for the Lord's coming",
    source: "Traditional Roman collect for the First Sunday of Advent",
    text: [
      "Stir up Thy power, we beseech Thee, O Lord, and come: that from the threatening dangers of our sins we may deserve to be rescued by Thy protection and to be saved by Thy deliverance. Who livest and reignest world without end. Amen.",
    ],
  },
  {
    slug: "christmas-midnight-collect",
    title: "Prayer for Christmas Night",
    category: "Liturgical year",
    keywords: ["Christmas", "Nativity", "night", "light", "Incarnation"],
    summary: "Give thanks for the true Light who shines in the darkness.",
    whenToPray: "On Christmas Eve or Christmas night",
    source: "Traditional Roman collect for Mass at Midnight on Christmas",
    text: [
      "O God, who hast made this most sacred night to shine forth with the brightness of the true Light: grant, we beseech Thee, that we who have known the mysteries of His light on earth may also enjoy His bliss in heaven. Who with Thee liveth and reigneth world without end. Amen.",
    ],
  },
  {
    slug: "epiphany-collect",
    title: "Prayer for the Epiphany",
    category: "Liturgical year",
    keywords: ["Epiphany", "Magi", "star", "nations", "adoration"],
    summary: "Follow the light of faith toward the unveiled glory of Christ.",
    whenToPray: "On the Epiphany of the Lord or during the Epiphany season",
    source: "Traditional Roman collect for the Epiphany",
    text: [
      "O God, who on this day didst reveal Thine only-begotten Son to the Gentiles by the guidance of a star: grant in Thy mercy that we, who know Thee now by faith, may be brought to behold the beauty of Thy majesty. Through the same Christ our Lord. Amen.",
    ],
  },
  {
    slug: "ash-wednesday-collect",
    title: "Prayer for the Beginning of Lent",
    category: "Liturgical year",
    keywords: ["Lent", "Ash Wednesday", "fasting", "penance", "conversion"],
    summary: "Enter the discipline of Lent with a steady and devoted heart.",
    whenToPray: "On Ash Wednesday or at the beginning of a Lenten fast",
    source: "Traditional Roman prayer for Ash Wednesday",
    text: [
      "Grant, O Lord, to Thy faithful people, that they may enter upon the venerable solemnities of fasting with fitting piety and go through them with steadfast devotion. Through Christ our Lord. Amen.",
    ],
  },
  {
    slug: "palm-sunday-collect",
    title: "Prayer for Palm Sunday",
    category: "Liturgical year",
    keywords: ["Palm Sunday", "Holy Week", "Passion", "humility", "Cross"],
    summary: "Learn the humility and endurance of the Saviour who accepted the Cross.",
    whenToPray: "On Palm Sunday or at the entrance into Holy Week",
    source: "Traditional Roman collect for Palm Sunday",
    text: [
      "Almighty and everlasting God, by whose ordinance our Saviour took flesh and suffered crucifixion to give mankind a pattern of humility: grant us this boon, that we may learn the lesson of His endurance and so deserve to share in His Resurrection. Through the same Christ our Lord. Amen.",
    ],
  },
  {
    slug: "easter-day-collect",
    title: "Prayer for Easter Day",
    category: "Liturgical year",
    keywords: ["Easter", "Resurrection", "Paschal", "eternal life", "victory"],
    summary: "Rejoice in Christ's victory over death and ask to live by his grace.",
    whenToPray: "On Easter Sunday and throughout the Easter season",
    source: "Traditional Roman collect for Easter Day",
    text: [
      "O God, who on this day through Thine only-begotten Son hast conquered death and unlocked for us the gate of eternity: help us to obtain the desires which Thou dost inspire, by Thy grace assisting us. Through the same Christ our Lord. Amen.",
    ],
  },
  {
    slug: "all-saints-day-collect",
    title: "Prayer for All Saints",
    category: "Liturgical year",
    keywords: ["All Saints", "saints", "heaven", "intercession", "November"],
    summary: "Join the whole communion of saints in seeking the mercy of God.",
    whenToPray: "On All Saints' Day or when invoking the communion of saints",
    source: "Traditional Roman collect for All Saints' Day",
    text: [
      "Almighty and everlasting God, who hast granted us to venerate in one solemnity the merits of all Thy Saints: we beseech Thee, that through the multitude of our intercessors Thou wouldst bestow upon us the desired abundance of Thy mercy. Through Christ our Lord. Amen.",
    ],
  },
  {
    slug: "immaculate-conception-collect",
    title: "Prayer for the Immaculate Conception",
    category: "Liturgical year",
    keywords: ["Immaculate Conception", "Mary", "December", "purity", "grace"],
    summary: "Honor the grace by which Mary was prepared as a worthy dwelling for the Son of God.",
    whenToPray: "On December 8 or during a novena for the Immaculate Conception",
    source: "Traditional Roman collect for the Immaculate Conception",
    text: [
      "O God, who by the Immaculate Conception of the Virgin didst prepare a worthy habitation for Thy Son: we beseech Thee, that as by the foreseen death of the same Thy Son Thou didst preserve her from all stain, so Thou wouldst grant us also, through her intercession, to come unto Thee with pure hearts. Through the same Christ our Lord. Amen.",
    ],
  },
  {
    slug: "annunciation-collect",
    title: "Prayer for the Annunciation",
    category: "Liturgical year",
    keywords: ["Annunciation", "Mary", "Gabriel", "Incarnation", "fiat"],
    summary: "Profess the Incarnation and ask the Mother of God to aid a faithful response.",
    whenToPray: "On March 25 or while discerning how to answer God's call",
    source: "Traditional Roman collect for the Annunciation",
    text: [
      "O God, who didst please that Thy Word should take flesh at the message of an Angel in the womb of the blessed Virgin Mary: grant to us Thy suppliants, that we who believe her to be truly the Mother of God may be aided by her intercession with Thee. Through the same Christ our Lord. Amen.",
    ],
  },
];

export const marianSeasonGuides: DevotionGuide[] = [
  {
    slug: "seven-sorrows-rosary",
    title: "The Rosary of the Seven Sorrows",
    category: "Marian devotion",
    eyebrow: "With Mary beside the suffering Christ",
    summary: "A complete chaplet through the seven sorrows of the Mother of God, with Scripture and repeated prayer.",
    duration: "25–35 minutes",
    provenance: "Traditional Servite devotion; meditation prompts written for Sanctum Council.",
    pastoralNote: "Use ordinary rosary beads by counting seven Hail Marys for each sorrow, or pray with a Seven Sorrows chaplet.",
    steps: [
      {
        title: "1. Open the chaplet",
        instruction: "Make the Sign of the Cross. Pray an Act of Contrition, then say: ‘My God, I offer Thee this Rosary for Thy glory, that I may honor Thy holy Mother by sharing and meditating upon her suffering. Grant me true repentance for my sins.’ Announce the first sorrow.",
      },
      {
        title: "2. The prophecy of Simeon",
        instruction: "Read the prophecy slowly. Ask for obedience when God's path carries a cost. Pray one Our Father and seven Hail Marys while remaining with Mary as the sword is foretold.",
        scripture: "Luke 2:22–35",
      },
      {
        title: "3. The flight into Egypt",
        instruction: "Contemplate the Holy Family leaving home at night under threat. Pray for refugees, endangered children, and families without security. Pray one Our Father and seven Hail Marys.",
        scripture: "Matthew 2:13–15",
      },
      {
        title: "4. The Child Jesus is lost in Jerusalem",
        instruction: "Enter Mary's three days of searching and the relief of finding Jesus in the Temple. Bring before God those who feel lost or far from faith. Pray one Our Father and seven Hail Marys.",
        scripture: "Luke 2:41–52",
      },
      {
        title: "5. Mary meets Jesus carrying the Cross",
        instruction: "This meeting is received in the Church's devotional tradition. See the Mother and Son remain united in love along the way of the Cross. Ask for courage to accompany another person's suffering. Pray one Our Father and seven Hail Marys.",
        scripture: "Traditional sorrow; Luke 23:26–31",
      },
      {
        title: "6. Mary stands beneath the Cross",
        instruction: "Stand with Mary and the beloved disciple as Jesus gives His life and entrusts His Mother to the Church. Keep a moment of silence, then pray one Our Father and seven Hail Marys.",
        scripture: "John 19:25–30",
      },
      {
        title: "7. Mary receives the body of Jesus",
        instruction: "Contemplate the sorrowful Mother receiving the wounded body of her Son. Commend the bereaved, the traumatized, and all who tend the dead. Pray one Our Father and seven Hail Marys.",
        scripture: "Mark 15:42–46",
      },
      {
        title: "8. Jesus is laid in the tomb",
        instruction: "Enter the silence of the sealed tomb with Mary. Place buried hopes and unanswered grief within her steadfast faith. Pray one Our Father and seven Hail Marys.",
        scripture: "John 19:38–42",
      },
      {
        title: "9. Close in hope",
        instruction: "Pray three Hail Marys in honor of the tears of the sorrowful Mother. Then pray: ‘V. Pray for us, O Virgin most sorrowful. R. That we may be made worthy of the promises of Christ. Let us pray. Lord Jesus, we now implore, both for the present and for the hour of our death, the intercession of the most Blessed Virgin Mary, Thy Mother, whose holy soul was pierced at the time of Thy Passion by a sword of grief. Grant us this favor, O Saviour of the world, who livest and reignest with the Father and the Holy Ghost, world without end. Amen.’ Make the Sign of the Cross and carry one suffering person into a concrete act of mercy.",
      },
    ],
  },
  {
    slug: "saint-joseph-novena-pattern",
    title: "Nine Days with Saint Joseph",
    category: "Novena",
    eyebrow: "Silence, courage, and faithful work",
    summary: "A complete, repeatable nine-day pattern of Scripture, petition, and quiet imitation of Saint Joseph.",
    duration: "10–15 minutes each day for nine days",
    provenance: "Original Sanctum Council novena pattern rooted in the Gospel accounts of Saint Joseph.",
    pastoralNote: "Choose one intention before the first day. Each day, make the Sign of the Cross, read the appointed Scripture, pray the Memorare to Saint Joseph, and close with an Our Father, Hail Mary, and Glory Be.",
    steps: [
      {
        title: "Day 1 — A just man",
        instruction: "Ask for integrity when no one sees and for a heart ready to place mercy above self-protection. Name your intention, read the passage, keep one minute of silence, and pray the daily closing prayers.",
        scripture: "Matthew 1:18–19",
      },
      {
        title: "Day 2 — Do not be afraid",
        instruction: "Bring God the fear surrounding your intention. Ask Saint Joseph to help you obey the Lord's word before every uncertainty is removed.",
        scripture: "Matthew 1:20–21",
      },
      {
        title: "Day 3 — He did as commanded",
        instruction: "Ask for prompt, concrete obedience. Identify one small duty you have delayed and resolve to complete it faithfully today.",
        scripture: "Matthew 1:22–25",
      },
      {
        title: "Day 4 — Guardian of the Redeemer",
        instruction: "Entrust children, vulnerable people, and the life of the Church to Saint Joseph's intercession. Ask what protection love requires from you.",
        scripture: "Matthew 2:13–15",
      },
      {
        title: "Day 5 — Refuge in exile",
        instruction: "Pray for displaced families, migrants, and all who are far from home. Offer one sacrifice for a person who lacks safety or belonging.",
        scripture: "Matthew 2:19–23",
      },
      {
        title: "Day 6 — The hidden life",
        instruction: "Give thanks for ordinary domestic life. Ask for holiness in meals, chores, relationships, and the unnoticed care that builds a home.",
        scripture: "Luke 2:39–40",
      },
      {
        title: "Day 7 — Faithful searching",
        instruction: "Bring before God anyone who seems lost. Ask for perseverance that searches without panic and receives Jesus again with gratitude.",
        scripture: "Luke 2:41–50",
      },
      {
        title: "Day 8 — The carpenter",
        instruction: "Place your labor, study, and material needs before God. Ask Saint Joseph for diligence without anxiety and for work ordered toward service rather than pride.",
        scripture: "Matthew 13:54–55",
      },
      {
        title: "Day 9 — Patron of a holy death",
        instruction: "Entrust your final hour and the dying to the care of Jesus, Mary, and Joseph. Renew your intention, thank God for every grace of these nine days, and pray the Prayer to Saint Joseph after the Rosary.",
        scripture: "Luke 2:51–52",
      },
    ],
  },
  {
    slug: "advent-prayer-walk",
    title: "An Advent Prayer Walk",
    category: "Liturgical season",
    eyebrow: "Make straight the way of the Lord",
    summary: "Walk slowly through the promises, persons, and places that prepare the heart for the coming of Christ.",
    duration: "25–40 minutes",
    provenance: "Original Sanctum Council Scripture walk shaped by the Church's Advent readings.",
    pastoralNote: "Walk somewhere safe and quiet, or use the stations seated indoors. Pause fully before moving to the next Scripture.",
    steps: [
      {
        title: "1. Begin in watchfulness",
        instruction: "Make the Sign of the Cross. Stand still and notice what is awake around you. Ask for freedom from spiritual drowsiness and name what you are waiting for from God.",
        scripture: "Mark 13:33–37",
      },
      {
        title: "2. Hear the promise",
        instruction: "Walk slowly while repeating: ‘O come, Emmanuel.’ Bring to God the barren or divided places that need the peace of the promised King.",
        scripture: "Isaiah 11:1–10",
      },
      {
        title: "3. Prepare the road",
        instruction: "Notice an obstacle in the path. Ask what habit, resentment, or distraction must be cleared so that Christ may enter more freely. Choose one act of repentance.",
        scripture: "Isaiah 40:3–5",
      },
      {
        title: "4. Receive the message",
        instruction: "Pause as Mary paused before Gabriel's word. Ask your honest question, then pray for the grace to say with her: ‘Be it done unto me according to thy word.’",
        scripture: "Luke 1:26–38",
      },
      {
        title: "5. Carry Christ to another",
        instruction: "Walk with Mary toward Elizabeth. Pray for one person by name and decide on one quiet visit, message, gift, or act of service that will bear Christ to them.",
        scripture: "Luke 1:39–45",
      },
      {
        title: "6. Trust with Saint Joseph",
        instruction: "Bring an unresolved decision before God. Release the demand to control every outcome and ask for the next obedient step, however ordinary.",
        scripture: "Matthew 1:18–24",
      },
      {
        title: "7. Make room",
        instruction: "End before a church, home, tree, or open sky. Imagine the poverty of Bethlehem. Offer Christ the room of your heart, pray the Saint Andrew Christmas Prayer, and close with the Glory Be.",
        scripture: "Luke 2:1–7",
      },
    ],
  },
];
